[package]
name = "cinnabar"
version = "0.1.0"
authors = ["Josh Lee <jleedev@gmail.com>"]

[dependencies]
mmap = "0.1.1"
rustc-serialize = "0.3"
flate2 = "0.2"
byteorder = "0.5"
bytes = { git = "https://github.com/carllerche/bytes" }
rust-crypto = "^0.2"

[[bin]]
name = "cinnabar"
doc = false
